services:

  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_volume:/data/db
    networks:
      - mongodb_network

  girder:
    build:
      context: .
    volumes:
      - girder_volume:/opt/girder
      - ./plugin:/app/girder/plugin
    networks:
      - mongodb_network
    ports:
      - 8086:8080
        
networks:
  mongodb_network:

volumes:
  mongodb_volume:
  girder_volume:
